{% set name = "coastal-cascade" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/UNC-CECL/cascade/archive/v{{ version }}.tar.gz
  sha256: c87e0a5834a9291be5958b803c1475c9a8a70fa0e3ee6f29d4d3e9f9c22811ff

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - baked-brie
    - barrier3d
    - imageio
    - joblib
    - matplotlib-base
    - numpy
    - pandas
    - pyyaml
    - scipy

test:
  imports:
    - cascade
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/UNC-CECL/cascade
  summary: 'The CoAStal Community-lAnDscape Evolution model'
  description: |
    Cascade represents decisions about coastal land-use (e.g., housing markets) and
    community-level mitigation measures using an empirically-grounded agent-based
    real estate model – the Coastal Home Ownership Model (chom).
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  doc_url: https://github.com/UNC-CECL/cascade
  dev_url: https://github.com/UNC-CECL/cascade

extra:
  recipe-maintainers:
    - mcflugen
    - anardek
